"use client";

import { Cake, Crown, Mail, MessageCircle, Plus, Search, ShoppingBag, UserRound, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { Modal } from "@/components/ui/modal";
import { PageHeader } from "@/components/ui/page-header";
import { StatCard } from "@/components/ui/stat-card";
import { useToast } from "@/components/ui/toast";
import { useStore } from "@/lib/store";
import type { Customer } from "@/lib/types";
import { currency, dateTime } from "@/lib/utils";

export default function CustomersPage() {
  const { state, addCustomer } = useStore();
  const toast = useToast();
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Customer | null>(state.customers[0] || null);
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ name: "", phone: "", email: "", cpf: "", birthDate: "", notes: "", consentMarketing: false });
  const customers = useMemo(() => state.customers.filter((c) => [c.name, c.phone, c.email, c.cpf].join(" ").toLowerCase().includes(query.toLowerCase())), [state.customers, query]);
  const customerSales = selected ? state.sales.filter((s) => s.customerId === selected.id && s.status === "completed") : [];
  const spent = customerSales.reduce((s, sale) => s + sale.total, 0);
  const topCustomer = state.customers.map((c) => ({ c, total: state.sales.filter((s) => s.customerId === c.id && s.status === "completed").reduce((sum, s) => sum + s.total, 0) })).sort((a, b) => b.total - a.total)[0];
  return <>
    <PageHeader title="Clientes · CRM" description="Histórico de compras, relacionamento, segmentação e fidelização." actions={<button className="btn-primary" onClick={() => setOpen(true)}><Plus size={18} /> Novo cliente</button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Clientes cadastrados" value={String(state.customers.length)} icon={Users} /><StatCard label="Clientes com compras" value={String(new Set(state.sales.map((s) => s.customerId).filter(Boolean)).size)} icon={ShoppingBag} tone="lime" /><StatCard label="Cliente destaque" value={topCustomer?.c.name || "—"} hint={topCustomer ? currency(topCustomer.total) : "Sem histórico"} icon={Crown} tone="warning" /><StatCard label="Consentimento de marketing" value={String(state.customers.filter((c) => c.consentMarketing).length)} icon={MessageCircle} tone="violet" /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[390px_1fr]">
      <section className="panel overflow-hidden"><div className="border-b border-line p-4"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={18} /><input className="input pl-10" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar cliente" /></div></div><div className="max-h-[680px] overflow-auto p-2">{customers.map((c) => { const count = state.sales.filter((s) => s.customerId === c.id && s.status === "completed").length; return <button key={c.id} onClick={() => setSelected(c)} className={`mb-1 flex w-full items-center gap-3 rounded-xl p-3 text-left transition ${selected?.id === c.id ? "bg-brand text-white" : "hover:bg-white/5"}`}><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-full font-bold ${selected?.id === c.id ? "bg-white/15" : "bg-brand/10 text-brand"}`}>{c.name.split(" ").map((x) => x[0]).slice(0, 2).join("")}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{c.name}</p><p className={`truncate text-xs ${selected?.id === c.id ? "text-white/70" : "text-slate-500"}`}>{c.phone} · {count} compras</p></div></button>; })}</div></section>
      <section className="panel p-5">{selected ? <><div className="flex flex-col gap-4 border-b border-line pb-5 md:flex-row md:items-start md:justify-between"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-brand text-xl font-black">{selected.name.split(" ").map((x) => x[0]).slice(0, 2).join("")}</div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black">{selected.name}</h2>{spent >= 500 && <span className="badge border-amber-500/30 bg-amber-500/10 text-amber-300"><Crown size={13} /> VIP</span>}</div><p className="mt-1 text-sm text-slate-400">{selected.phone}</p><p className="text-sm text-slate-500">{selected.email || "E-mail não informado"}</p></div></div><div className="flex gap-2"><a className="btn-ghost" href={`https://wa.me/55${selected.phone.replace(/\D/g, "")}`} target="_blank" rel="noreferrer"><MessageCircle size={17} /> WhatsApp</a>{selected.email && <a className="btn-ghost" href={`mailto:${selected.email}`}><Mail size={17} /> E-mail</a>}</div></div>
      <div className="grid gap-3 py-5 sm:grid-cols-3"><div className="stat"><p className="text-xs text-slate-500">Total gasto</p><p className="mt-1 text-xl font-black text-lime">{currency(spent)}</p></div><div className="stat"><p className="text-xs text-slate-500">Compras</p><p className="mt-1 text-xl font-black">{customerSales.length}</p></div><div className="stat"><p className="text-xs text-slate-500">Ticket médio</p><p className="mt-1 text-xl font-black">{currency(customerSales.length ? spent / customerSales.length : 0)}</p></div></div>
      <div className="grid gap-5 lg:grid-cols-[1fr_300px]"><div><h3 className="mb-3 font-bold">Histórico de compras</h3>{customerSales.length ? <div className="space-y-3">{customerSales.map((sale) => <div key={sale.id} className="panel-soft flex items-center justify-between gap-4 p-3"><div><p className="font-semibold">Venda #{sale.number}</p><p className="text-xs text-slate-500">{dateTime(sale.createdAt)} · {sale.items.map((i) => i.name).join(", ")}</p></div><p className="font-black text-lime">{currency(sale.total)}</p></div>)}</div> : <div className="panel-soft grid min-h-40 place-items-center text-sm text-slate-500">Nenhuma compra vinculada a este cliente.</div>}</div><div className="space-y-3"><div className="panel-soft p-4"><div className="mb-2 flex items-center gap-2 font-bold"><Cake className="text-brand" size={18} /> Informações</div><p className="text-sm text-slate-400">Nascimento: {selected.birthDate || "Não informado"}</p><p className="mt-1 text-sm text-slate-400">CPF: {selected.cpf || "Não informado"}</p></div><div className="panel-soft p-4"><div className="mb-2 flex items-center gap-2 font-bold"><UserRound className="text-brand" size={18} /> Observações</div><p className="text-sm leading-6 text-slate-400">{selected.notes || "Nenhuma observação registrada."}</p></div><div className={`panel-soft p-4 text-sm ${selected.consentMarketing ? "text-lime" : "text-amber-300"}`}>{selected.consentMarketing ? "Cliente autorizou comunicações promocionais." : "Cliente não autorizou comunicações promocionais."}</div></div></div></> : <div className="grid min-h-[560px] place-items-center text-slate-500">Selecione um cliente.</div>}</section>
    </div>
    <Modal open={open} onClose={() => setOpen(false)} title="Novo cliente" width="max-w-xl"><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); const customer = addCustomer(form); setSelected(customer); setOpen(false); setForm({ name: "", phone: "", email: "", cpf: "", birthDate: "", notes: "", consentMarketing: false }); toast.success("Cliente cadastrado."); }}><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1.5 block text-sm font-semibold">Nome</span><input className="input" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span className="mb-1.5 block text-sm font-semibold">Telefone</span><input className="input" required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label><span className="mb-1.5 block text-sm font-semibold">E-mail</span><input className="input" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label><span className="mb-1.5 block text-sm font-semibold">CPF</span><input className="input" value={form.cpf} onChange={(e) => setForm({ ...form, cpf: e.target.value })} /></label><label><span className="mb-1.5 block text-sm font-semibold">Nascimento</span><input className="input" type="date" value={form.birthDate} onChange={(e) => setForm({ ...form, birthDate: e.target.value })} /></label><label className="sm:col-span-2"><span className="mb-1.5 block text-sm font-semibold">Observações</span><textarea className="input min-h-24" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><label className="flex items-start gap-3 rounded-xl border border-line p-3 text-sm"><input type="checkbox" className="mt-1" checked={form.consentMarketing} onChange={(e) => setForm({ ...form, consentMarketing: e.target.checked })} /><span><strong>Consentimento de marketing</strong><span className="mt-1 block text-xs text-slate-500">Registre apenas quando houver autorização do cliente para receber ofertas e campanhas.</span></span></label><div className="flex justify-end gap-2"><button type="button" className="btn-ghost" onClick={() => setOpen(false)}>Cancelar</button><button className="btn-primary">Cadastrar cliente</button></div></form></Modal>
  </>;
}
