"use client";

import { Minus, Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { useStore } from "@/lib/store";
import type { ComboComponent, Product, ProductKind } from "@/lib/types";

const empty = { name: "", barcode: "", sku: "", category: "Bebidas", brand: "", kind: "unit" as ProductKind, price: 0, cost: 0, stock: 0, minStock: 0, active: true, bottleVolumeMl: 1000, dosePrices: { "50": 15, "100": 28, "200": 52 }, comboItems: [] as ComboComponent[] };

export function ProductForm({ product, initialBarcode, onSave, onCancel }: { product?: Product; initialBarcode?: string; onSave: (data: Partial<Product> & Pick<Product, "name" | "barcode" | "category" | "price" | "cost">) => void; onCancel: () => void }) {
  const { state } = useStore();
  const [form, setForm] = useState({ ...empty, ...(product || {}), barcode: initialBarcode || product?.barcode || "" });
  const [componentId, setComponentId] = useState("");
  const [componentQty, setComponentQty] = useState(1);
  useEffect(() => setForm({ ...empty, ...(product || {}), barcode: initialBarcode || product?.barcode || "" }), [product, initialBarcode]);
  const set = (key: string, value: string | number | boolean) => setForm((f) => ({ ...f, [key]: value }));
  return (
    <form className="space-y-5" onSubmit={(e) => { e.preventDefault(); if (form.kind === "combo" && !form.comboItems.length) { window.alert("Adicione pelo menos um componente antes de ativar/salvar um combo."); return; } onSave({ ...form, id: product?.id, active: form.active ?? product?.active ?? true, price: Number(form.price), cost: Number(form.cost), stock: Number(form.stock), minStock: Number(form.minStock), bottleVolumeMl: form.kind === "volume" ? Number(form.bottleVolumeMl) : undefined, dosePrices: form.kind === "volume" ? form.dosePrices : undefined, comboItems: form.kind === "combo" ? form.comboItems : undefined }); }}>
      <div className="grid gap-4 md:grid-cols-2">
        <label className="md:col-span-2"><span className="mb-1.5 block text-sm font-semibold">Nome do produto</span><input className="input" required value={form.name} onChange={(e) => set("name", e.target.value)} placeholder="Ex.: Heineken Long Neck 330ml" /></label>
        <label><span className="mb-1.5 block text-sm font-semibold">Código de barras</span><input className="input" autoFocus={Boolean(initialBarcode)} value={form.barcode} onChange={(e) => set("barcode", e.target.value)} placeholder="Bipe ou digite o EAN" /><span className="mt-1 block text-[11px] text-slate-500">Pode ficar em branco no cadastro inicial e ser vinculado depois com o leitor.</span></label>
        <label><span className="mb-1.5 block text-sm font-semibold">SKU interno</span><input className="input" value={form.sku} onChange={(e) => set("sku", e.target.value)} placeholder="Gerado automaticamente" /></label>
        <label><span className="mb-1.5 block text-sm font-semibold">Categoria</span><input className="input" required value={form.category} onChange={(e) => set("category", e.target.value)} /></label>
        <label><span className="mb-1.5 block text-sm font-semibold">Marca</span><input className="input" value={form.brand || ""} onChange={(e) => set("brand", e.target.value)} /></label>
        <label><span className="mb-1.5 block text-sm font-semibold">Tipo de controle</span><select className="select" value={form.kind} onChange={(e) => set("kind", e.target.value)}><option value="unit">Unidade</option><option value="volume">Garrafa / dose</option><option value="combo">Combo</option></select></label>
        {form.kind === "volume" && <label><span className="mb-1.5 block text-sm font-semibold">Volume da garrafa (ml)</span><input className="input" type="number" min="1" value={form.bottleVolumeMl || 1000} onChange={(e) => set("bottleVolumeMl", Number(e.target.value))} /></label>}
        {form.kind === "volume" && <div className="md:col-span-2 rounded-xl border border-line bg-white/[0.03] p-4"><p className="mb-3 text-sm font-semibold">Preços por dose</p><div className="grid gap-3 sm:grid-cols-3">{[50, 100, 200].map((ml) => <label key={ml}><span className="mb-1.5 block text-xs text-slate-400">Dose {ml} ml</span><input className="input" type="number" min="0" step="0.01" value={form.dosePrices?.[String(ml)] || 0} onChange={(e) => setForm((f) => ({ ...f, dosePrices: { ...f.dosePrices, [String(ml)]: Number(e.target.value) } }))} /></label>)}</div></div>}
        {form.kind === "combo" && <div className="md:col-span-2 rounded-xl border border-line bg-white/[0.03] p-4"><p className="mb-3 text-sm font-semibold">Composição do combo</p><div className="grid gap-2 sm:grid-cols-[1fr_110px_auto]"><select className="select" value={componentId} onChange={(e) => setComponentId(e.target.value)}><option value="">Selecione um produto</option>{state.products.filter((p) => p.kind !== "combo" && p.id !== product?.id).map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="input" type="number" min="1" step="1" value={componentQty} onChange={(e) => setComponentQty(Number(e.target.value))} /><button type="button" className="btn-primary" onClick={() => { if (!componentId || componentQty <= 0) return; setForm((f) => ({ ...f, comboItems: [...f.comboItems.filter((item) => item.productId !== componentId), { productId: componentId, quantity: componentQty }] })); setComponentId(""); setComponentQty(1); }}><Plus size={16} /> Incluir</button></div><div className="mt-3 space-y-2">{form.comboItems.map((item) => { const itemProduct = state.products.find((p) => p.id === item.productId); return <div key={item.productId} className="flex items-center justify-between rounded-lg border border-line bg-black/20 px-3 py-2 text-sm"><span>{item.quantity}× {itemProduct?.name || "Produto removido"}</span><button type="button" className="rounded-lg p-1.5 text-red-300 hover:bg-red-500/10" onClick={() => setForm((f) => ({ ...f, comboItems: f.comboItems.filter((x) => x.productId !== item.productId) }))}><Minus size={15} /></button></div>; })}{!form.comboItems.length && <p className="text-xs text-slate-500">Adicione os produtos que serão baixados quando o combo for vendido.</p>}</div></div>}
        <label className="md:col-span-2 flex items-center justify-between rounded-xl border border-line bg-white/[0.03] p-4"><div><span className="block text-sm font-semibold">Produto ativo no PDV</span><span className="mt-1 block text-xs text-slate-500">Desative enquanto o código, estoque, preço ou composição ainda estiverem sendo conferidos.</span></div><input type="checkbox" className="h-5 w-5 accent-fuchsia-500" checked={Boolean(form.active)} onChange={(e) => set("active", e.target.checked)} /></label>
        <label><span className="mb-1.5 block text-sm font-semibold">Preço de custo</span><input className="input" type="number" min="0" step="0.01" required value={form.cost} onChange={(e) => set("cost", Number(e.target.value))} /></label>
        <label><span className="mb-1.5 block text-sm font-semibold">Preço de venda</span><input className="input" type="number" min="0" step="0.01" required value={form.price} onChange={(e) => set("price", Number(e.target.value))} /></label>
        {form.kind !== "combo" && <><label><span className="mb-1.5 block text-sm font-semibold">Estoque atual</span><input className="input" type="number" min="0" step="1" value={form.stock} onChange={(e) => set("stock", Number(e.target.value))} /></label><label><span className="mb-1.5 block text-sm font-semibold">Estoque mínimo</span><input className="input" type="number" min="0" step="1" value={form.minStock} onChange={(e) => set("minStock", Number(e.target.value))} /></label></>}
      </div>
      <div className="rounded-xl border border-line bg-white/[0.03] p-3 text-xs text-slate-400">Leitores USB e Bluetooth que funcionam como teclado são aceitos. O leitor normalmente envia o código e a tecla Enter automaticamente.</div>
      <div className="flex justify-end gap-2"><button type="button" className="btn-ghost" onClick={onCancel}>Cancelar</button><button className="btn-primary">Salvar produto</button></div>
    </form>
  );
}
