"use client";

import { CalendarClock, CheckCircle2, CircleDollarSign, Plus, ReceiptText, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { Modal } from "@/components/ui/modal";
import { PageHeader } from "@/components/ui/page-header";
import { StatCard } from "@/components/ui/stat-card";
import { useToast } from "@/components/ui/toast";
import { dashboardMetrics } from "@/lib/business";
import { useStore } from "@/lib/store";
import type { FinancialEntry } from "@/lib/types";
import { currency, dateOnly, todayIso } from "@/lib/utils";

export default function FinancePage() {
  const { state, addFinancialEntry, updateFinancialEntry } = useStore();
  const toast = useToast();
  const [view, setView] = useState<"resumo" | "contas">("resumo");
  const [open, setOpen] = useState(false);
  const [type, setType] = useState<"income" | "expense">("expense");
  const [form, setForm] = useState({ description: "", category: "Operacional", amount: 0, dueDate: todayIso(), status: "pending" as "pending" | "paid", supplierId: "", recurring: false });
  const metrics = dashboardMetrics(state);
  const entries = useMemo(() => state.financialEntries.filter((entry) => !entry.saleId).sort((a, b) => (b.dueDate || b.date).localeCompare(a.dueDate || a.date)), [state.financialEntries]);
  const pending = entries.filter((entry) => (entry.status || "paid") === "pending");
  const pendingPay = pending.filter((entry) => entry.type === "expense").reduce((sum, entry) => sum + entry.amount, 0);
  const pendingReceive = pending.filter((entry) => entry.type === "income").reduce((sum, entry) => sum + entry.amount, 0);
  const paidExpenses = state.financialEntries.filter((entry) => entry.type === "expense" && (entry.status || "paid") === "paid").reduce((sum, entry) => sum + entry.amount, 0);
  const salesRevenue = state.sales.filter((sale) => sale.status === "completed").reduce((sum, sale) => sum + sale.total, 0);

  const resetForm = (nextType: "income" | "expense") => {
    setType(nextType);
    setForm({ description: "", category: nextType === "expense" ? "Operacional" : "Outras receitas", amount: 0, dueDate: todayIso(), status: "pending", supplierId: "", recurring: false });
    setOpen(true);
  };

  const markPaid = (entry: FinancialEntry) => {
    try { updateFinancialEntry(entry.id, { status: "paid", paidAt: new Date().toISOString(), date: new Date().toISOString() }); toast.success(entry.type === "expense" ? "Conta marcada como paga." : "Recebimento confirmado."); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível atualizar."); }
  };

  return <>
    <PageHeader title="Financeiro" description="Primeiro o essencial: quanto entrou, quanto saiu e o que vence. Detalhes ficam em uma segunda camada." actions={<div className="flex gap-2"><button className="btn-ghost" onClick={() => resetForm("income")}><Plus size={17} /> Receita</button><button className="btn-primary" onClick={() => resetForm("expense")}><Plus size={17} /> Despesa</button></div>} />

    <div className="mb-4 flex gap-2"><button className={view === "resumo" ? "btn-primary" : "btn-ghost"} onClick={() => setView("resumo")}>Resumo</button><button className={view === "contas" ? "btn-primary" : "btn-ghost"} onClick={() => setView("contas")}>Contas a pagar / receber</button></div>

    {view === "resumo" ? <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Vendas" value={currency(salesRevenue)} hint="Balcão + marketplaces" icon={TrendingUp} tone="lime" /><StatCard label="Despesas pagas" value={currency(paidExpenses)} icon={TrendingDown} tone="brand" /><StatCard label="Lucro líquido estimado" value={currency(metrics.netProfit)} hint="Vendas + outras receitas - CMV - despesas" icon={CircleDollarSign} tone={metrics.netProfit >= 0 ? "lime" : "warning"} /><StatCard label="Contas pendentes" value={currency(pendingPay)} hint={`${pending.filter((entry) => entry.type === "expense").length} lançamentos`} icon={CalendarClock} tone="warning" /></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><section className="panel p-5"><h2 className="section-title">Leitura rápida</h2><p className="muted">Os três números que precisam ser conferidos todos os dias.</p><div className="mt-5 space-y-3"><div className="panel-soft flex items-center justify-between p-4"><span className="text-slate-400">Entrou em vendas</span><strong className="text-lime">{currency(salesRevenue)}</strong></div><div className="panel-soft flex items-center justify-between p-4"><span className="text-slate-400">Saiu em despesas pagas</span><strong className="text-brand">{currency(paidExpenses)}</strong></div><div className="panel-soft flex items-center justify-between p-4"><span className="text-slate-400">Ainda precisa pagar</span><strong className="text-amber-300">{currency(pendingPay)}</strong></div><div className="panel-soft flex items-center justify-between p-4"><span className="text-slate-400">Ainda precisa receber</span><strong className="text-cyan-300">{currency(pendingReceive)}</strong></div></div></section><section className="panel p-5"><h2 className="section-title">Próximos vencimentos</h2><p className="muted">O que exige ação primeiro.</p><div className="mt-4 space-y-2">{pending.slice(0, 8).map((entry) => <div key={entry.id} className="panel-soft flex items-center gap-3 p-3"><div className={`grid h-10 w-10 place-items-center rounded-xl ${entry.type === "expense" ? "bg-brand/10 text-brand" : "bg-lime/10 text-lime"}`}>{entry.type === "expense" ? <TrendingDown size={18} /> : <TrendingUp size={18} />}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{entry.description}</p><p className="text-xs text-slate-500">Vence {dateOnly(entry.dueDate || entry.date)} · {entry.category}</p></div><strong className={entry.type === "expense" ? "text-brand" : "text-lime"}>{currency(entry.amount)}</strong></div>)}{!pending.length && <div className="grid min-h-40 place-items-center text-sm text-lime">Nenhuma conta pendente.</div>}</div></section></div>
    </> : <section className="panel p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="section-title">Contas</h2><p className="muted">Um clique para baixar. Nada de preencher o mesmo dado duas vezes.</p></div><WalletCards className="text-brand" size={22} /></div><div className="table-wrap"><table className="table"><thead><tr><th>Vencimento</th><th>Descrição</th><th>Tipo</th><th>Fornecedor</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id}><td>{dateOnly(entry.dueDate || entry.date)}</td><td><div className="font-semibold">{entry.description}</div><div className="text-xs text-slate-500">{entry.category}{entry.recurring ? " · recorrente" : ""}</div></td><td><span className="badge">{entry.type === "expense" ? "Pagar" : "Receber"}</span></td><td>{state.suppliers.find((supplier) => supplier.id === entry.supplierId)?.name || "—"}</td><td className={entry.type === "expense" ? "font-black text-brand" : "font-black text-lime"}>{currency(entry.amount)}</td><td>{(entry.status || "paid") === "paid" ? <span className="badge border-lime/30 bg-lime/10 text-lime">Pago</span> : <span className="badge border-amber-500/30 bg-amber-500/10 text-amber-300">Pendente</span>}</td><td>{(entry.status || "paid") === "pending" && <button className="btn-lime py-2" onClick={() => markPaid(entry)}><CheckCircle2 size={15} /> {entry.type === "expense" ? "Pagar" : "Receber"}</button>}</td></tr>)}</tbody></table>{!entries.length && <div className="grid min-h-40 place-items-center text-sm text-slate-500">Nenhum lançamento manual.</div>}</div></section>}

    <Modal open={open} onClose={() => setOpen(false)} title={type === "expense" ? "Nova conta / despesa" : "Nova receita"} width="max-w-lg"><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); try { addFinancialEntry({ type, category: form.category, description: form.description, amount: Number(form.amount), date: new Date().toISOString(), dueDate: form.dueDate, status: form.status, paidAt: form.status === "paid" ? new Date().toISOString() : undefined, supplierId: form.supplierId || undefined, recurring: form.recurring }); toast.success("Lançamento salvo."); setOpen(false); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível salvar."); } }}><label><span className="mb-1.5 block text-sm font-semibold">Descrição</span><input className="input" autoFocus required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder={type === "expense" ? "Ex.: Energia / fornecedor" : "Ex.: Receita adicional"} /></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1.5 block text-sm font-semibold">Valor</span><input className="input" type="number" min="0.01" step="0.01" required value={form.amount} onChange={(event) => setForm({ ...form, amount: Number(event.target.value) })} /></label><label><span className="mb-1.5 block text-sm font-semibold">Vencimento</span><input className="input" type="date" required value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} /></label></div><label><span className="mb-1.5 block text-sm font-semibold">Categoria</span><input className="input" value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} /></label>{type === "expense" && <label><span className="mb-1.5 block text-sm font-semibold">Fornecedor (opcional)</span><select className="select" value={form.supplierId} onChange={(event) => setForm({ ...form, supplierId: event.target.value })}><option value="">Nenhum</option>{state.suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label>}<div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl border border-line p-3"><input type="checkbox" checked={form.status === "paid"} onChange={(event) => setForm({ ...form, status: event.target.checked ? "paid" : "pending" })} /> <span className="text-sm">Já foi {type === "expense" ? "pago" : "recebido"}</span></label><label className="flex items-center gap-2 rounded-xl border border-line p-3"><input type="checkbox" checked={form.recurring} onChange={(event) => setForm({ ...form, recurring: event.target.checked })} /> <span className="text-sm">Recorrente</span></label></div><button className="btn-primary w-full"><ReceiptText size={18} /> Salvar lançamento</button></form></Modal>
  </>;
}
