"use client";

import { ArrowDownCircle, ArrowUpCircle, CalendarDays, CircleDollarSign, Plus, Receipt, Scale, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import { Modal } from "@/components/ui/modal";
import { PageHeader } from "@/components/ui/page-header";
import { StatCard } from "@/components/ui/stat-card";
import { useToast } from "@/components/ui/toast";
import { dashboardMetrics } from "@/lib/business";
import { useStore } from "@/lib/store";
import { currency, dateOnly } from "@/lib/utils";

export default function FinancePage() {
  const { state, addFinancialEntry } = useStore();
  const toast = useToast();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ type: "expense" as "income" | "expense", category: "Despesas operacionais", description: "", amount: 0, date: new Date().toISOString().slice(0, 10) });
  const metrics = dashboardMetrics(state);
  const income = state.financialEntries.filter((e) => e.type === "income").reduce((s, e) => s + e.amount, 0);
  const expenses = state.financialEntries.filter((e) => e.type === "expense").reduce((s, e) => s + e.amount, 0);
  const byDay = useMemo(() => {
    const map = new Map<string, { income: number; expense: number }>();
    state.financialEntries.forEach((e) => { const day = e.date.slice(0, 10); const current = map.get(day) || { income: 0, expense: 0 }; current[e.type] += e.amount; map.set(day, current); });
    return Array.from(map.entries()).sort(([a], [b]) => a.localeCompare(b)).slice(-7);
  }, [state.financialEntries]);
  const max = Math.max(1, ...byDay.flatMap(([, v]) => [v.income, v.expense]));
  return <>
    <PageHeader title="Financeiro" description="Fluxo de caixa, despesas, resultado e indicadores de rentabilidade." actions={<button className="btn-primary" onClick={() => setOpen(true)}><Plus size={18} /> Novo lançamento</button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Receitas" value={currency(income)} icon={ArrowUpCircle} tone="lime" /><StatCard label="Despesas" value={currency(expenses)} icon={ArrowDownCircle} tone="brand" /><StatCard label="Lucro bruto estimado" value={currency(metrics.grossProfit)} icon={TrendingUp} tone="violet" /><StatCard label="Resultado líquido" value={currency(metrics.netProfit)} icon={Scale} tone={metrics.netProfit >= 0 ? "lime" : "warning"} /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <section className="panel p-5"><div className="mb-5"><h2 className="section-title">Fluxo dos últimos dias</h2><p className="muted">Entradas e saídas registradas</p></div>{byDay.length ? <div className="flex h-72 items-end gap-3 overflow-x-auto border-b border-line px-2 pb-2">{byDay.map(([day, values]) => <div key={day} className="flex min-w-20 flex-1 flex-col items-center gap-2"><div className="flex h-52 items-end gap-1.5"><div title={`Entradas ${currency(values.income)}`} className="w-6 rounded-t-md bg-lime" style={{ height: `${Math.max(3, values.income / max * 100)}%` }} /><div title={`Saídas ${currency(values.expense)}`} className="w-6 rounded-t-md bg-brand" style={{ height: `${Math.max(3, values.expense / max * 100)}%` }} /></div><span className="text-xs text-slate-500">{day.slice(5).split("-").reverse().join("/")}</span></div>)}</div> : <div className="grid h-72 place-items-center text-slate-500">Sem dados financeiros.</div>}<div className="mt-4 flex gap-4 text-xs text-slate-400"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-lime" /> Entradas</span><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-brand" /> Saídas</span></div></section>
      <section className="panel p-5"><div className="mb-5"><h2 className="section-title">DRE simplificada</h2><p className="muted">Resultado acumulado do período</p></div><div className="space-y-3 text-sm"><div className="flex justify-between border-b border-line pb-3"><span className="text-slate-400">Receita bruta de vendas</span><strong className="text-lime">{currency(metrics.totalRevenue)}</strong></div><div className="flex justify-between border-b border-line pb-3"><span className="text-slate-400">Custos estimados dos produtos</span><strong>{currency(metrics.totalRevenue - metrics.grossProfit)}</strong></div><div className="flex justify-between border-b border-line pb-3"><span className="text-slate-400">Lucro bruto</span><strong>{currency(metrics.grossProfit)}</strong></div><div className="flex justify-between border-b border-line pb-3"><span className="text-slate-400">Despesas operacionais</span><strong className="text-brand">- {currency(expenses)}</strong></div><div className="flex items-end justify-between pt-2"><span className="font-bold">Lucro líquido estimado</span><strong className={`text-2xl ${metrics.netProfit >= 0 ? "text-lime" : "text-red-300"}`}>{currency(metrics.netProfit)}</strong></div></div></section>
    </div>
    <section className="panel mt-6 p-5"><div className="mb-4 flex items-center gap-2"><Receipt className="text-brand" size={20} /><h2 className="section-title">Lançamentos</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th>Canal</th><th>Valor</th></tr></thead><tbody>{state.financialEntries.map((e) => <tr key={e.id}><td>{dateOnly(e.date)}</td><td><span className={`badge ${e.type === "income" ? "border-lime/30 bg-lime/10 text-lime" : "border-brand/30 bg-brand/10 text-pink-300"}`}>{e.type === "income" ? "Entrada" : "Saída"}</span></td><td>{e.category}</td><td>{e.description}</td><td>{e.channel || "—"}</td><td className={`font-black ${e.type === "income" ? "text-lime" : "text-brand"}`}>{e.type === "income" ? "+ " : "- "}{currency(e.amount)}</td></tr>)}</tbody></table></div></section>
    <Modal open={open} onClose={() => setOpen(false)} title="Novo lançamento financeiro" width="max-w-lg"><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); addFinancialEntry({ ...form, amount: Number(form.amount), date: new Date(form.date + "T12:00:00").toISOString() }); setOpen(false); setForm({ type: "expense", category: "Despesas operacionais", description: "", amount: 0, date: new Date().toISOString().slice(0, 10) }); toast.success("Lançamento registrado."); }}><label><span className="mb-1.5 block text-sm font-semibold">Tipo</span><select className="select" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as "income" | "expense" })}><option value="expense">Despesa / saída</option><option value="income">Receita / entrada</option></select></label><label><span className="mb-1.5 block text-sm font-semibold">Categoria</span><input className="input" required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label><span className="mb-1.5 block text-sm font-semibold">Descrição</span><input className="input" required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-sm font-semibold">Valor</span><input className="input" type="number" min="0.01" step="0.01" required value={form.amount} onChange={(e) => setForm({ ...form, amount: Number(e.target.value) })} /></label><label><span className="mb-1.5 block text-sm font-semibold">Data</span><input className="input" type="date" required value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label></div><div className="flex justify-end gap-2"><button type="button" className="btn-ghost" onClick={() => setOpen(false)}>Cancelar</button><button className="btn-primary">Salvar lançamento</button></div></form></Modal>
  </>;
}
