"use client";

import { AlertTriangle, CheckCircle2, CloudCog, KeyRound, PlugZap, RefreshCw, ShieldCheck, Webhook } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { useToast } from "@/components/ui/toast";
import { useStore } from "@/lib/store";
import { dateTime } from "@/lib/utils";

export default function IntegrationsPage() {
  const { state, setIntegrationEnabled } = useStore();
  const toast = useToast();
  return <>
    <PageHeader title="Integrações" description="Central de iFood e 99Food, pronta para credenciais oficiais e conciliação por canal." />
    <div className="mb-6 rounded-2xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm leading-6 text-amber-100"><div className="mb-1 flex items-center gap-2 font-bold"><AlertTriangle size={18} /> Ativação real depende das plataformas</div>As APIs oficiais exigem credenciais, aprovação da loja e permissões liberadas pelo iFood e 99Food. Os botões abaixo registram a configuração do projeto, mas não criam acesso não autorizado nem usam métodos paralelos.</div>
    <div className="grid gap-6 xl:grid-cols-2">{state.integrations.map((integration) => { const isIfood = integration.platform === "iFood"; return <section key={integration.platform} className="panel overflow-hidden"><div className={`h-2 ${isIfood ? "bg-red-500" : "bg-yellow-400"}`} /><div className="p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-3"><div className={`grid h-12 w-12 place-items-center rounded-xl text-lg font-black ${isIfood ? "bg-red-500 text-white" : "bg-yellow-400 text-black"}`}>{isIfood ? "iF" : "99"}</div><div><h2 className="text-xl font-black">{integration.platform}</h2><p className="text-sm text-slate-500">{integration.accountName}</p></div></div></div><span className={`badge ${integration.enabled ? "border-lime/30 bg-lime/10 text-lime" : "border-slate-600 bg-white/5 text-slate-400"}`}>{integration.enabled ? <CheckCircle2 size={14} /> : <PlugZap size={14} />}{integration.enabled ? "Configurada" : "Desconectada"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="panel-soft p-4"><p className="text-xs text-slate-500">Comissão cadastrada</p><p className="mt-1 text-2xl font-black">{integration.commissionRate}%</p></div><div className="panel-soft p-4"><p className="text-xs text-slate-500">Última sincronização</p><p className="mt-1 font-bold">{integration.lastSync ? dateTime(integration.lastSync) : "Nunca"}</p></div></div><div className="mt-5 space-y-3"><div className="panel-soft flex items-start gap-3 p-3"><CloudCog className="mt-0.5 text-brand" size={19} /><div><p className="font-semibold">Importação de pedidos</p><p className="text-xs leading-5 text-slate-500">Pedidos normalizados entram no sistema e podem gerar baixa de estoque, financeiro e conciliação.</p></div></div><div className="panel-soft flex items-start gap-3 p-3"><RefreshCw className="mt-0.5 text-lime" size={19} /><div><p className="font-semibold">Vinculação de produtos</p><p className="text-xs leading-5 text-slate-500">Cada item externo precisa ser relacionado a um produto ou combo interno antes da baixa.</p></div></div></div><button className={integration.enabled ? "btn-danger mt-5 w-full" : "btn-primary mt-5 w-full"} onClick={() => { setIntegrationEnabled(integration.platform, !integration.enabled); toast.success(integration.enabled ? `${integration.platform} desativado.` : `Configuração de ${integration.platform} marcada como ativa.`); }}>{integration.enabled ? "Desativar configuração" : "Marcar credenciais como configuradas"}</button></div></section>; })}</div>
    <section className="panel mt-6 p-5"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-brand/10 p-2.5 text-brand"><Webhook size={22} /></div><div><h2 className="section-title">Webhook normalizado</h2><p className="muted">Ponto seguro para middleware oficial enviar pedidos ao sistema</p></div></div><div className="grid gap-4 lg:grid-cols-3"><div className="panel-soft p-4"><KeyRound className="mb-3 text-brand" size={22} /><p className="font-bold">Autenticação por segredo</p><p className="mt-1 text-sm leading-6 text-slate-500">Use o cabeçalho <code className="text-slate-300">x-webhook-secret</code> com uma chave forte.</p></div><div className="panel-soft p-4"><ShieldCheck className="mb-3 text-lime" size={22} /><p className="font-bold">Idempotência</p><p className="mt-1 text-sm leading-6 text-slate-500">O identificador externo impede que o mesmo pedido seja processado duas vezes.</p></div><div className="panel-soft p-4"><CloudCog className="mb-3 text-violet-300" size={22} /><p className="font-bold">Endpoint</p><code className="mt-2 block break-all rounded-lg bg-black/30 p-2 text-xs text-slate-300">POST /api/integrations/orders</code></div></div></section>
  </>;
}
