-- Beb's Gestão - schema inicial de produção
-- Execute no SQL Editor de um projeto Supabase novo.
create extension if not exists pgcrypto;

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  document text,
  phone text,
  address text,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  role text not null check (role in ('admin','manager','cashier','stock','finance')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  unique(company_id, name)
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  category_id uuid references public.categories(id) on delete set null,
  name text not null,
  barcode text not null,
  sku text not null,
  brand text,
  kind text not null default 'unit' check (kind in ('unit','volume','combo')),
  price numeric(14,2) not null default 0 check (price >= 0),
  cost numeric(14,2) not null default 0 check (cost >= 0),
  stock numeric(14,3) not null default 0 check (stock >= 0),
  min_stock numeric(14,3) not null default 0 check (min_stock >= 0),
  bottle_volume_ml integer,
  open_volume_ml integer not null default 0 check (open_volume_ml >= 0),
  dose_prices jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id, barcode),
  unique(company_id, sku)
);

create table if not exists public.combo_items (
  combo_product_id uuid not null references public.products(id) on delete cascade,
  component_product_id uuid not null references public.products(id) on delete restrict,
  quantity numeric(14,3) not null check (quantity > 0),
  dose_ml integer,
  primary key (combo_product_id, component_product_id)
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  phone text not null,
  email text,
  cpf text,
  birth_date date,
  notes text,
  consent_marketing boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.cash_sessions (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  operator_id uuid references public.profiles(id),
  status text not null check (status in ('open','closed')),
  opening_amount numeric(14,2) not null default 0,
  closing_amount numeric(14,2),
  opened_at timestamptz not null default now(),
  closed_at timestamptz
);

create unique index if not exists one_open_cash_per_company on public.cash_sessions(company_id) where status = 'open';

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  cash_session_id uuid references public.cash_sessions(id),
  customer_id uuid references public.customers(id),
  number bigint generated by default as identity,
  channel text not null check (channel in ('Balcão','iFood','99Food')),
  external_id text,
  subtotal numeric(14,2) not null,
  discount numeric(14,2) not null default 0,
  total numeric(14,2) not null,
  status text not null default 'completed' check (status in ('completed','cancelled')),
  operator_id uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  unique(company_id, channel, external_id)
);

create table if not exists public.sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales(id) on delete cascade,
  product_id uuid not null references public.products(id),
  name text not null,
  mode text not null check (mode in ('unit','dose','combo')),
  quantity numeric(14,3) not null check (quantity > 0),
  unit_price numeric(14,2) not null,
  dose_ml integer
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales(id) on delete cascade,
  method text not null,
  amount numeric(14,2) not null check (amount >= 0)
);

create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  product_id uuid not null references public.products(id),
  sale_id uuid references public.sales(id),
  type text not null,
  quantity numeric(14,3) not null default 0,
  volume_ml integer,
  reason text not null,
  operator_id uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.cash_movements (
  id uuid primary key default gen_random_uuid(),
  cash_session_id uuid not null references public.cash_sessions(id) on delete cascade,
  type text not null check (type in ('opening','closing','sale','withdrawal','supply','expense')),
  amount numeric(14,2) not null,
  description text not null,
  operator_id uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.financial_entries (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  sale_id uuid references public.sales(id),
  type text not null check (type in ('income','expense')),
  category text not null,
  description text not null,
  amount numeric(14,2) not null check (amount >= 0),
  entry_date date not null default current_date,
  channel text,
  created_at timestamptz not null default now()
);

create table if not exists public.external_product_links (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  platform text not null check (platform in ('iFood','99Food')),
  external_sku text not null,
  product_id uuid not null references public.products(id),
  unique(company_id, platform, external_sku)
);

create table if not exists public.integrations (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  platform text not null check (platform in ('iFood','99Food')),
  account_name text,
  enabled boolean not null default false,
  commission_rate numeric(6,3) not null default 0,
  last_sync timestamptz,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(company_id, platform)
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  actor_id uuid references public.profiles(id),
  action text not null,
  entity text not null,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.consume_product(p_product_id uuid, p_quantity numeric, p_dose_ml integer, p_sale_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  p public.products%rowtype;
  remaining integer;
  open_ml integer;
  sealed numeric;
begin
  select * into p from public.products where id = p_product_id for update;
  if not found then raise exception 'Produto não encontrado: %', p_product_id; end if;
  if p_dose_ml is not null then
    remaining := (p_dose_ml * p_quantity)::integer;
    open_ml := coalesce(p.open_volume_ml, 0);
    sealed := p.stock;
    if open_ml + (sealed * coalesce(p.bottle_volume_ml,0)) < remaining then raise exception 'Volume insuficiente para %', p.name; end if;
    while remaining > 0 loop
      if open_ml <= 0 then sealed := sealed - 1; open_ml := p.bottle_volume_ml; end if;
      if remaining >= open_ml then remaining := remaining - open_ml; open_ml := 0; else open_ml := open_ml - remaining; remaining := 0; end if;
    end loop;
    update public.products set stock = sealed, open_volume_ml = open_ml, updated_at = now() where id = p.id;
    insert into public.stock_movements(company_id, product_id, sale_id, type, volume_ml, reason) values(p.company_id, p.id, p_sale_id, 'sale_dose', -(p_dose_ml * p_quantity)::integer, 'Venda externa');
  else
    if p.stock < p_quantity then raise exception 'Estoque insuficiente para %', p.name; end if;
    update public.products set stock = stock - p_quantity, updated_at = now() where id = p.id;
    insert into public.stock_movements(company_id, product_id, sale_id, type, quantity, reason) values(p.company_id, p.id, p_sale_id, 'sale', -p_quantity, 'Venda externa');
  end if;
end $$;

create or replace function public.process_external_order(payload jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_company uuid;
  v_sale uuid;
  v_item jsonb;
  v_product uuid;
  v_channel text := payload->>'platform';
  v_external text := payload->>'externalId';
  v_subtotal numeric := 0;
  v_total numeric := coalesce((payload->>'total')::numeric, 0);
  v_discount numeric := coalesce((payload->>'discount')::numeric, 0);
begin
  select company_id into v_company from public.integrations where platform = v_channel and enabled = true order by created_at limit 1;
  if v_company is null then raise exception 'Integração % não está habilitada', v_channel; end if;
  select id into v_sale from public.sales where company_id = v_company and channel = v_channel and external_id = v_external;
  if v_sale is not null then return jsonb_build_object('status','duplicate','sale_id',v_sale); end if;

  for v_item in select * from jsonb_array_elements(payload->'items') loop
    v_subtotal := v_subtotal + ((v_item->>'unitPrice')::numeric * (v_item->>'quantity')::numeric);
  end loop;

  insert into public.sales(company_id, channel, external_id, subtotal, discount, total, status, created_at)
  values(v_company, v_channel, v_external, v_subtotal, v_discount, v_total, 'completed', coalesce((payload->>'createdAt')::timestamptz, now()))
  returning id into v_sale;

  for v_item in select * from jsonb_array_elements(payload->'items') loop
    v_product := null;
    if nullif(v_item->>'internalProductId','') is not null then v_product := (v_item->>'internalProductId')::uuid; end if;
    if v_product is null and nullif(v_item->>'externalSku','') is not null then
      select product_id into v_product from public.external_product_links where company_id = v_company and platform = v_channel and external_sku = v_item->>'externalSku';
    end if;
    if v_product is null then raise exception 'Item externo sem vínculo: %', v_item->>'name'; end if;
    insert into public.sale_items(sale_id, product_id, name, mode, quantity, unit_price, dose_ml)
    values(v_sale, v_product, v_item->>'name', case when v_item ? 'doseMl' then 'dose' else 'unit' end, (v_item->>'quantity')::numeric, (v_item->>'unitPrice')::numeric, nullif(v_item->>'doseMl','')::integer);
    perform public.consume_product(v_product, (v_item->>'quantity')::numeric, nullif(v_item->>'doseMl','')::integer, v_sale);
  end loop;

  insert into public.payments(sale_id, method, amount) values(v_sale, coalesce(payload->>'paymentMethod','Marketplace'), v_total);
  insert into public.financial_entries(company_id, sale_id, type, category, description, amount, entry_date, channel) values(v_company, v_sale, 'income', 'Vendas ' || v_channel, 'Pedido externo ' || v_external, v_total, current_date, v_channel);
  update public.integrations set last_sync = now() where company_id = v_company and platform = v_channel;
  return jsonb_build_object('status','processed','sale_id',v_sale);
end $$;

alter table public.companies enable row level security;
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.combo_items enable row level security;
alter table public.customers enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.payments enable row level security;
alter table public.stock_movements enable row level security;
alter table public.cash_sessions enable row level security;
alter table public.cash_movements enable row level security;
alter table public.financial_entries enable row level security;
alter table public.external_product_links enable row level security;
alter table public.integrations enable row level security;
alter table public.audit_logs enable row level security;

create or replace function public.current_company_id() returns uuid language sql stable security definer set search_path = public as $$ select company_id from public.profiles where id = auth.uid() $$;

create policy "profiles own company" on public.profiles for select to authenticated using (company_id = public.current_company_id());
create policy "products own company" on public.products for all to authenticated using (company_id = public.current_company_id()) with check (company_id = public.current_company_id());
create policy "customers own company" on public.customers for all to authenticated using (company_id = public.current_company_id()) with check (company_id = public.current_company_id());
create policy "sales own company" on public.sales for all to authenticated using (company_id = public.current_company_id()) with check (company_id = public.current_company_id());
create policy "cash sessions own company" on public.cash_sessions for all to authenticated using (company_id = public.current_company_id()) with check (company_id = public.current_company_id());
create policy "financial own company" on public.financial_entries for all to authenticated using (company_id = public.current_company_id()) with check (company_id = public.current_company_id());
create policy "integrations own company" on public.integrations for all to authenticated using (company_id = public.current_company_id()) with check (company_id = public.current_company_id());
create policy "audit own company" on public.audit_logs for select to authenticated using (company_id = public.current_company_id());


create policy "companies own record" on public.companies for select to authenticated using (id = public.current_company_id());
create policy "companies update own record" on public.companies for update to authenticated using (id = public.current_company_id()) with check (id = public.current_company_id());
create policy "categories own company" on public.categories for all to authenticated using (company_id = public.current_company_id()) with check (company_id = public.current_company_id());
create policy "combo items own company" on public.combo_items for all to authenticated
using (exists (select 1 from public.products p where p.id = combo_product_id and p.company_id = public.current_company_id()))
with check (exists (select 1 from public.products p where p.id = combo_product_id and p.company_id = public.current_company_id()));
create policy "sale items own company" on public.sale_items for all to authenticated
using (exists (select 1 from public.sales s where s.id = sale_id and s.company_id = public.current_company_id()))
with check (exists (select 1 from public.sales s where s.id = sale_id and s.company_id = public.current_company_id()));
create policy "payments own company" on public.payments for all to authenticated
using (exists (select 1 from public.sales s where s.id = sale_id and s.company_id = public.current_company_id()))
with check (exists (select 1 from public.sales s where s.id = sale_id and s.company_id = public.current_company_id()));
create policy "stock movements own company" on public.stock_movements for all to authenticated using (company_id = public.current_company_id()) with check (company_id = public.current_company_id());
create policy "cash movements own company" on public.cash_movements for all to authenticated
using (exists (select 1 from public.cash_sessions c where c.id = cash_session_id and c.company_id = public.current_company_id()))
with check (exists (select 1 from public.cash_sessions c where c.id = cash_session_id and c.company_id = public.current_company_id()));
create policy "external links own company" on public.external_product_links for all to authenticated using (company_id = public.current_company_id()) with check (company_id = public.current_company_id());


-- Segurança das funções SECURITY DEFINER.
-- Funções de baixa/processamento externo não ficam expostas ao navegador.
revoke execute on function public.consume_product(uuid, numeric, integer, uuid) from public, anon, authenticated, service_role;
revoke execute on function public.process_external_order(jsonb) from public, anon, authenticated;
grant execute on function public.process_external_order(jsonb) to service_role;

-- current_company_id é necessária nas policies dos usuários autenticados.
revoke execute on function public.current_company_id() from public, anon;
grant execute on function public.current_company_id() to authenticated;
